--
-- Structure of the `ACCOUNT_TYPE` table
--

CREATE TABLE `ACCOUNT_TYPE` (
  `ID` int(11) NOT NULL,
  `TYPE` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ACCOUNT_TYPE`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `UK_TYPE` (`TYPE`);
COMMIT;

--
-- Structure of the `ACCOUNT`
--

CREATE TABLE `ACCOUNT` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ACCOUNT_TYPE` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ACCOUNT`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `UK_NAME` (`NAME`),
  ADD KEY `FK_ACCOUNT_TYPE` (`ACCOUNT_TYPE`);

ALTER TABLE `ACCOUNT`
  ADD CONSTRAINT `FK_ACCOUNT_TYPE` FOREIGN KEY (`ACCOUNT_TYPE`) REFERENCES `ACCOUNT_TYPE` (`ID`);
COMMIT;