CREATE TABLE `ACCOUNT_TYPE` (
  `ID_ACCOUNT_TYPE` int(11) NOT NULL,
  `TYPE` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ACCOUNT_TYPE`
  ADD PRIMARY KEY (`ID_ACCOUNT_TYPE`),
  ADD UNIQUE KEY `TYPE` (`TYPE`);

ALTER TABLE `ACCOUNT_TYPE`
  MODIFY `ID_ACCOUNT_TYPE` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;
